---
displayName: Credits Check
type: middleware
import: github.com/tcassaert/traefik-plugin-credits_check
summary: 'Check credits of user before allowing the request'
testData:
  url: 'localhost:5000'
